### ISSUE TITLE
Fix Ringer Starup Issue

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Ringer-Client-Desktop#47]
### Description
Ringer won't  start in the development environment and instead will pop up with a window showing this error: 
```
    [1] Error: EEXIST: file already exists, mkdir 'C:\Users\btb5s\AppData\Roaming\Electron'
    [1]     at mkdirSync (fs.js:731:3)
    [1]     at Object.fs.mkdirSync (ELECTRON_ASAR.js:721:16)
    [1]     at ElectronStore._ensureDirectory (C:\Users\btb5s\Documents\GitHub\Ringer-Client-Desktop\node_modules\conf\dist\source\index.js:358:12)
    [1]     at ElectronStore.get store [as store] (C:\Users\btb5s\Documents\GitHub\Ringer-Client-Desktop\node_modules\conf\dist\source\index.js:284:22)
    [1]     at new Conf (C:\Users\btb5s\Documents\GitHub\Ringer-Client-Desktop\node_modules\conf\dist\source\index.js:131:32)
    [1]     at new ElectronStore (C:\Users\btb5s\Documents\GitHub\Ringer-Client-Desktop\node_modules\electron-store\index.js:69:3)
    [1]     at Object.<anonymous> (C:\Users\btb5s\Documents\GitHub\Ringer-Client-Desktop\main.js:12:15)
    [1]     at Object.<anonymous> (C:\Users\btb5s\Documents\GitHub\Ringer-Client-Desktop\main.js:135:3)
    [1]     at Module._compile (internal/modules/cjs/loader.js:693:30)
    [1]     at Object.require.extensions.(anonymous function) [as .js] (C:\Users\btb5s\Documents\GitHub\Ringer-Client-Desktop\node_modules\electron-compile\lib\require-hook.js:77:14)
```

### To Reproduce
1. Head to the terminal and navigate to the root directory of Ringer-Client-Desktop
2. Run `yarn ringer-start`

### Expected behavior
Ringer should launch as normal but as we can see, it is throwing this error. It is unknown if this is a code issue or if it is isolated to 1 system. 

### Screenshots
Will Add Screenshots Later

### Desktop
 - OS: Windows
 - Version: 11

**Comment by Superior126** [comment]
### Update 1
Still no progress on this issue. 

**Tried:**
1. Removing the `node_modules` folder and reinstalling dependencies 
2. Updating dependencies: `yarn upgrade` 
3. Clearing npm-cache

**Comment by Superior126** [comment]
### Update 2
The issue that has been created on this doesn't appear to be getting any attention. We may have to switch to a different library as this one appears to be having problems.

**Comment by Superior126** [comment]
### Update 3
The first error is resolved by upgrading all dependencies however there is another error with `bundle.js`. 
```bash
[19440:1108/170708.841:ERROR:CONSOLE(5566)] "SyntaxError: Unexpected token & in JSON at position 580314", source: chrome-devtools://devtools/bundled/shell.js (5566)
```
As well as this on in the dev tools: 
```bash
bundle.js:53509 Uncaught ReferenceError: globalThis is not defined
    at bundle.js:53509
    at bundle.js:54006
    at bundle.js:54023
```

**Comment by Superior126** [comment]
### Problem Resolved
The issue was fixed by changing the node version the app was running with to the latest version.
